// flow-typed signature: 9b7d3749d9cccd82aaa9a6cf3de4cfce
// flow-typed version: <<STUB>>/ensure-dir_v^0.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ensure-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ensure-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ensure-dir/index' {
  declare module.exports: $Exports<'ensure-dir'>;
}
declare module 'ensure-dir/index.js' {
  declare module.exports: $Exports<'ensure-dir'>;
}
