// flow-typed signature: c49b88026e5511b9026787a07be73e93
// flow-typed version: <<STUB>>/postcss-viewport-units_v^0.1.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-viewport-units'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-viewport-units' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-viewport-units/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-viewport-units/index' {
  declare module.exports: $Exports<'postcss-viewport-units'>;
}
declare module 'postcss-viewport-units/index.js' {
  declare module.exports: $Exports<'postcss-viewport-units'>;
}
declare module 'postcss-viewport-units/test/index.js' {
  declare module.exports: $Exports<'postcss-viewport-units/test/index'>;
}
