// flow-typed signature: 8cc62331bc45e77fa41dd3c6fcfeab30
// flow-typed version: <<STUB>>/react-sizes_v^0.0.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sizes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sizes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sizes/lib/Sizes' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/utils/get-display-name' {
  declare module.exports: any;
}

declare module 'react-sizes/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sizes/index' {
  declare module.exports: $Exports<'react-sizes'>;
}
declare module 'react-sizes/index.js' {
  declare module.exports: $Exports<'react-sizes'>;
}
declare module 'react-sizes/lib/Sizes.js' {
  declare module.exports: $Exports<'react-sizes/lib/Sizes'>;
}
declare module 'react-sizes/lib/utils/get-display-name.js' {
  declare module.exports: $Exports<'react-sizes/lib/utils/get-display-name'>;
}
declare module 'react-sizes/lib/utils/index.js' {
  declare module.exports: $Exports<'react-sizes/lib/utils/index'>;
}
