// flow-typed signature: 8ca4c04bd2fdc8de1c5770ed191b2e1d
// flow-typed version: <<STUB>>/svg-sprite-loader_v^2.0.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-sprite-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-sprite-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-sprite-loader/examples/base-webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/icon' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/svg-to-icon-component-runtime-generator' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/extract-sprite/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/extract-sprite/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/extract-sprite/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/server-side-rendering/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/server-side-rendering/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/server-side-rendering/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/configurator' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/exceptions' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/plugin' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/runtime-generator' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/plugin' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/runtime/browser-sprite.build' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/runtime/browser-sprite' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/runtime/sprite.build' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/runtime/sprite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-sprite-loader/examples/base-webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/base-webpack.config'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite/build/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/build/main'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/icon.jsx' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/icon'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/main.jsx' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/main'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/svg-to-icon-component-runtime-generator.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/svg-to-icon-component-runtime-generator'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/extract-sprite/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/extract-sprite/build/main'>;
}
declare module 'svg-sprite-loader/examples/extract-sprite/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/extract-sprite/main'>;
}
declare module 'svg-sprite-loader/examples/extract-sprite/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/extract-sprite/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/server-side-rendering/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/server-side-rendering/build/main'>;
}
declare module 'svg-sprite-loader/examples/server-side-rendering/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/server-side-rendering/main'>;
}
declare module 'svg-sprite-loader/examples/server-side-rendering/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/server-side-rendering/webpack.config'>;
}
declare module 'svg-sprite-loader/lib/config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/config'>;
}
declare module 'svg-sprite-loader/lib/configurator.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/configurator'>;
}
declare module 'svg-sprite-loader/lib/exceptions.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/exceptions'>;
}
declare module 'svg-sprite-loader/lib/loader.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/loader'>;
}
declare module 'svg-sprite-loader/lib/plugin.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/plugin'>;
}
declare module 'svg-sprite-loader/lib/runtime-generator.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/runtime-generator'>;
}
declare module 'svg-sprite-loader/lib/utils.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils'>;
}
declare module 'svg-sprite-loader/plugin.js' {
  declare module.exports: $Exports<'svg-sprite-loader/plugin'>;
}
declare module 'svg-sprite-loader/runtime/browser-sprite.build.js' {
  declare module.exports: $Exports<'svg-sprite-loader/runtime/browser-sprite.build'>;
}
declare module 'svg-sprite-loader/runtime/browser-sprite.js' {
  declare module.exports: $Exports<'svg-sprite-loader/runtime/browser-sprite'>;
}
declare module 'svg-sprite-loader/runtime/sprite.build.js' {
  declare module.exports: $Exports<'svg-sprite-loader/runtime/sprite.build'>;
}
declare module 'svg-sprite-loader/runtime/sprite.js' {
  declare module.exports: $Exports<'svg-sprite-loader/runtime/sprite'>;
}
