// flow-typed signature: 05b7d75221ff9fc6f0e0fe0698208664
// flow-typed version: <<STUB>>/symlink-webpack-plugin_v^0.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'symlink-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'symlink-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'symlink-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'symlink-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'symlink-webpack-plugin/src/index'>;
}
