// flow-typed signature: 26ed04114e1fae3a6c6b7b91eaf2e818
// flow-typed version: <<STUB>>/viewport-units-buggyfill_v^0.6.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'viewport-units-buggyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'viewport-units-buggyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'viewport-units-buggyfill/viewport-units-buggyfill.hacks' {
  declare module.exports: any;
}

declare module 'viewport-units-buggyfill/viewport-units-buggyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'viewport-units-buggyfill/viewport-units-buggyfill.hacks.js' {
  declare module.exports: $Exports<'viewport-units-buggyfill/viewport-units-buggyfill.hacks'>;
}
declare module 'viewport-units-buggyfill/viewport-units-buggyfill.js' {
  declare module.exports: $Exports<'viewport-units-buggyfill/viewport-units-buggyfill'>;
}
