// flow-typed signature: 1d77505de29d6f286e46c1d509b917e4
// flow-typed version: <<STUB>>/randgen_v^0.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'randgen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'randgen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'randgen/lib/randgen' {
  declare module.exports: any;
}

declare module 'randgen/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'randgen/index' {
  declare module.exports: $Exports<'randgen'>;
}
declare module 'randgen/index.js' {
  declare module.exports: $Exports<'randgen'>;
}
declare module 'randgen/lib/randgen.js' {
  declare module.exports: $Exports<'randgen/lib/randgen'>;
}
declare module 'randgen/test.js' {
  declare module.exports: $Exports<'randgen/test'>;
}
