// flow-typed signature: f2d0c2252bfe5d289c34744b252a2473
// flow-typed version: <<STUB>>/cli-spinners_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-spinners' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cli-spinners/index' {
  declare module.exports: $Exports<'cli-spinners'>;
}
declare module 'cli-spinners/index.js' {
  declare module.exports: $Exports<'cli-spinners'>;
}
