// flow-typed signature: ac2a9633a9b3f54a879a7fec1d2cfbaa
// flow-typed version: <<STUB>>/html-imports-loader_v^1.5.6/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-imports-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-imports-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-imports-loader/react/generateTemplate' {
  declare module.exports: any;
}

declare module 'html-imports-loader/react/htmlModuleLoader' {
  declare module.exports: any;
}

declare module 'html-imports-loader/react/index' {
  declare module.exports: any;
}

declare module 'html-imports-loader/react/syncEvent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-imports-loader/index' {
  declare module.exports: $Exports<'html-imports-loader'>;
}
declare module 'html-imports-loader/index.js' {
  declare module.exports: $Exports<'html-imports-loader'>;
}
declare module 'html-imports-loader/react/generateTemplate.js' {
  declare module.exports: $Exports<'html-imports-loader/react/generateTemplate'>;
}
declare module 'html-imports-loader/react/htmlModuleLoader.js' {
  declare module.exports: $Exports<'html-imports-loader/react/htmlModuleLoader'>;
}
declare module 'html-imports-loader/react/index.js' {
  declare module.exports: $Exports<'html-imports-loader/react/index'>;
}
declare module 'html-imports-loader/react/syncEvent.js' {
  declare module.exports: $Exports<'html-imports-loader/react/syncEvent'>;
}
